services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manhlan
      POSTGRES_DB: secondCRUD
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:manhlan@127.0.0.1/secondCRUD"

volumes:
  postgres_data: